:scheduler:
  :schedule:
    set_monthly_winner:
      cron: "0 0 1 * *" # At midnight on 1st day of every month
#      cron: '0 0 * * * *' # hourly
      class: "MonthlyWinnerWorker"
      queue: "default"
      description: "Run service monthly to determine two winners among users who made orders last month"